language: objective-c
osx_image: xcode8.1

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Napi.xcodeproj
  - SCHEME=Napi

script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage version
  - carthage build --no-skip-current --platform mac
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" ONLY_ACTIVE_ARCH=NO -sdk macosx10.12 build | xcpretty
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" ONLY_ACTIVE_ARCH=NO -sdk macosx10.12 test | xcpretty
